# Generated by Django 3.0.7 on 2020-06-13 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Memmber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_no', models.IntegerField(unique=True)),
                ('fullname', models.CharField(max_length=50)),
                ('address1', models.CharField(max_length=50)),
                ('address2', models.CharField(max_length=50)),
                ('address3', models.CharField(max_length=50)),
                ('opening_invest', models.IntegerField(default=0)),
                ('closing_invest', models.IntegerField(default=0)),
                ('opening_loan', models.IntegerField(default=0)),
                ('closing_loan', models.IntegerField(default=0)),
                ('mobile_no', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('active', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Weekly_entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField()),
                ('invest_amt', models.IntegerField(default=100)),
                ('loan_amt', models.IntegerField(default=0)),
                ('interest_amt', models.IntegerField(default=0)),
                ('remarks', models.CharField(max_length=50)),
                ('memmber_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Memmber')),
            ],
        ),
        migrations.CreateModel(
            name='loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_date', models.DateField()),
                ('loan_amt', models.IntegerField()),
                ('remarks', models.CharField(max_length=50)),
                ('memmber_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Memmber')),
            ],
        ),
    ]
