# Generated by Django 3.0.7 on 2020-06-13 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200613_0807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memmber',
            name='closing_loan',
        ),
        migrations.RemoveField(
            model_name='memmber',
            name='opening_loan',
        ),
        migrations.AlterField(
            model_name='weekly_entry',
            name='remarks',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
