# Generated by Django 3.0.7 on 2020-06-14 14:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200614_0524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weekly_entry',
            name='entry_date',
            field=models.DateField(default=datetime.datetime(2020, 6, 14, 14, 52, 52, 99538)),
        ),
    ]
