# Generated by Django 3.0.7 on 2020-06-20 04:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20200620_0416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='loan_date',
            field=models.DateField(default=datetime.datetime(2020, 6, 20, 4, 20, 9, 435251)),
        ),
        migrations.AlterField(
            model_name='memmber',
            name='mobile_no',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='weekly_entry',
            name='entry_date',
            field=models.DateField(default=datetime.datetime(2020, 6, 20, 4, 20, 9, 434512)),
        ),
    ]
