# Generated by Django 3.0.7 on 2020-06-21 07:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20200620_0421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='loan_date',
            field=models.DateField(default=datetime.datetime(2020, 6, 21, 7, 42, 16, 80473)),
        ),
        migrations.AlterField(
            model_name='weekly_entry',
            name='entry_date',
            field=models.DateField(default=datetime.datetime(2020, 6, 21, 7, 42, 16, 79756)),
        ),
        migrations.CreateModel(
            name='loan_interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime(2020, 6, 21, 7, 42, 16, 81117))),
                ('interest_amt', models.IntegerField(default=0)),
                ('memmber_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Memmber')),
            ],
        ),
    ]
