# Generated by Django 3.0.7 on 2020-06-24 05:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20200621_0830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memmber',
            name='closing_invest',
        ),
        migrations.RemoveField(
            model_name='memmber',
            name='opening_invest',
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_date',
            field=models.DateField(default=datetime.datetime(2020, 6, 24, 5, 34, 41, 238959)),
        ),
        migrations.AlterField(
            model_name='loan_interest',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 6, 24, 5, 34, 41, 239741)),
        ),
        migrations.AlterField(
            model_name='loan_interest',
            name='interest_amt',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='weekly_entry',
            name='entry_date',
            field=models.DateField(default=datetime.datetime(2020, 6, 24, 5, 34, 41, 238208)),
        ),
        migrations.AlterField(
            model_name='weekly_entry',
            name='interest_amt',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='weekly_entry',
            name='invest_amt',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='weekly_entry',
            name='loan_amt',
            field=models.IntegerField(),
        ),
    ]
