# Generated by Django 3.0.7 on 2020-06-24 14:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20200624_0534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memmber',
            name='email',
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_date',
            field=models.DateField(default=datetime.datetime(2020, 6, 24, 14, 48, 19, 638969)),
        ),
        migrations.AlterField(
            model_name='loan_interest',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 6, 24, 14, 48, 19, 639603)),
        ),
        migrations.AlterField(
            model_name='weekly_entry',
            name='entry_date',
            field=models.DateField(default=datetime.datetime(2020, 6, 24, 14, 48, 19, 638253)),
        ),
    ]
