# Generated by Django 3.2.2 on 2021-05-08 06:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20200624_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='memmber',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_date',
            field=models.DateField(verbose_name=datetime.datetime(2021, 5, 8, 6, 1, 51, 174325, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='loan_interest',
            name='date',
            field=models.DateField(verbose_name=datetime.datetime(2021, 5, 8, 6, 1, 51, 175009, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='weekly_entry',
            name='entry_date',
            field=models.DateField(verbose_name=datetime.datetime(2021, 5, 8, 6, 1, 51, 173539, tzinfo=utc)),
        ),
    ]
