# Generated by Django 3.2.2 on 2021-05-09 16:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20210508_0601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weekly_entry',
            name='interest_amt',
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_date',
            field=models.DateField(verbose_name=datetime.datetime(2021, 5, 9, 16, 24, 11, 139304, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='loan_interest',
            name='date',
            field=models.DateField(verbose_name=datetime.datetime(2021, 5, 9, 16, 24, 11, 139995, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='weekly_entry',
            name='entry_date',
            field=models.DateField(verbose_name=datetime.datetime(2021, 5, 9, 16, 24, 11, 138519, tzinfo=utc)),
        ),
    ]
